spring:
   application:
     name: handler
   profiles: 
    active: dev
   jackson:
    serialization:
      indent-output: true
kafka:
  bootstrap-servers: localhost:29092
  consumer:
    key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    group.id: producer-api
    auto.offset.reset: earliest
  producer:
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8088
logging:
  level:
    ROOT: INFO